# Generated by Django 2.0.4 on 2018-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('Unit', models.IntegerField()),
                ('Bedrooms', models.IntegerField()),
                ('FullBath', models.IntegerField()),
                ('HalfBath', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
